# Kubernetes version: v1
# Purpose: Defines sensitive configuration data and credentials for Hotel Management ERP microservices
# Security: Enhanced with AES-256 encryption, automated rotation, and strict access controls

apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: hotel-erp
  annotations:
    rotation.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    secret.kubernetes.io/managed-by: "hotel-erp"
    secret.kubernetes.io/classification: "restricted"
    encryption.kubernetes.io/encryption-provider: "aws-kms"
    backup.kubernetes.io/retention: "90d"
type: Opaque
data:
  POSTGRES_USER: UE9TVEdSRVNfVVNFUg== # Base64 encoded placeholder
  POSTGRES_PASSWORD: UE9TVEdSRVNfUEFTU1dPUkQ= # Base64 encoded placeholder
  POSTGRES_DB: SE9URUxfRVJQX0RC # Base64 encoded placeholder
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGhvc3Q6NTQzMi9kYg== # Base64 encoded placeholder
  DATABASE_CONNECTION_POOL_SIZE: MTA= # Base64 encoded placeholder
  DATABASE_SSL_MODE: cmVxdWlyZQ== # Base64 encoded placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: hotel-erp
  annotations:
    rotation.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    secret.kubernetes.io/managed-by: "hotel-erp"
    secret.kubernetes.io/classification: "restricted"
    encryption.kubernetes.io/encryption-provider: "aws-kms"
    backup.kubernetes.io/retention: "90d"
type: Opaque
data:
  REDIS_PASSWORD: UkVESVNfUEFTU1dPUkQ= # Base64 encoded placeholder
  REDIS_URL: cmVkaXM6Ly9ob3N0OjYzNzk= # Base64 encoded placeholder
  REDIS_PORT: NjM3OQ== # Base64 encoded placeholder
  REDIS_TLS_ENABLED: dHJ1ZQ== # Base64 encoded placeholder
  REDIS_CLUSTER_MODE: dHJ1ZQ== # Base64 encoded placeholder
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: hotel-erp
  annotations:
    rotation.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    secret.kubernetes.io/managed-by: "hotel-erp"
    secret.kubernetes.io/classification: "restricted"
    encryption.kubernetes.io/encryption-provider: "aws-kms"
    backup.kubernetes.io/retention: "90d"
type: Opaque
data:
  JWT_SECRET_KEY: SldUX1NFQ1JFVF9LRVk= # Base64 encoded placeholder
  JWT_REFRESH_KEY: SldUX1JFRlJFU0hfS0VZ # Base64 encoded placeholder
  TOKEN_EXPIRY: MmgwbQ== # Base64 encoded placeholder (2 hours)
  TOKEN_REFRESH_EXPIRY: N2QwbQ== # Base64 encoded placeholder (7 days)
  TOKEN_ISSUER: aG90ZWwtZXJwLXN5c3RlbQ== # Base64 encoded placeholder
  TOKEN_ALGORITHM: SFMyNTY= # Base64 encoded placeholder (HS256)